name: LoanDataServices_MSSQL_CDC
definitionId: b5ea17b1-f170-46dc-bc31-cc744ca984c1
connectionConfiguration:
  host: ${SQLSERVER_HOST}
  port: ${SQLSERVER_PORT}
  database: LoanDataServices
  username: ${SQLSERVER_USERNAME}
  password: ${SQLSERVER_PASSWORD}
  schema: dbo
  replication_method: CDC
  ssl: false
  trustServerCertificate: true
  include_tables:
    - Customers
    - Loan
    - LoanInstallment
    - LoanHistory
